# Generated by Django 3.1.2 on 2020-11-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('user_type', models.CharField(blank=True, choices=[('A', 'ADMIN'), ('D', 'DOCTOR'), ('P', 'PATIENT')], max_length=400, null=True)),
                ('user_password', models.CharField(blank=True, max_length=150, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
