# Generated by Django 3.1.2 on 2020-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='user_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='websiteuser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('G', 'Good'), ('NG', 'Not Good')], max_length=150, null=True),
        ),
    ]
